server:
  port: 9092
  
spring:
  application:
    name: Patient-Registration-Management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehrDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      
management:
  health:
    circuitbreakers:
      enabled: true
    endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: health

      
resilience4j:
  circuitbreaker:
    instances:
      medicalRecordBreaker:
        SlidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberofCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 10
        waitDurationInOpenState: 65

eureka:
  instance:
    prefer-ip-address:  true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
